name: Mirror topic from Discourse
on: 
  workflow_dispatch:
#  schedule:
#    - cron: '10 * * * *'

jobs:
  check-topic-changes:
    runs-on: ubuntu-latest
    steps:
      - run: topic_content=$(curl https://discourse.charmhub.io/raw/5834)
      - id: get_topic_info
        run: |
            topic_info=$(curl https://discourse.charmhub.io/t/5834.json | jq '.post_stream.posts')
            echo "::set-output name=topic_info::$topic_info" 
            
      - run: echo ${{ steps.get_topic_info.outputs.topic_info }}
