name: Mirror topic from Discourse
on: 
  workflow_dispatch:
#  schedule:
#    - cron: '10 * * * *'

jobs:
  check-topic-changes:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://discourse.charmhub.io/raw/5834
